export const userRows = [
    {
        id: 1957,
        nama_ortu: "Dessy",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1958,
        nama_ortu: "Desta",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://media.creativemornings.com/uploads/user/avatar/49419/Bechtel_Profile_Square.jpg"
    },
    {
        id: 1959,
        nama_ortu: "Ani",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1960,
        nama_ortu: "Budi",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://media.creativemornings.com/uploads/user/avatar/49419/Bechtel_Profile_Square.jpg"
    },
    {
        id: 1961,
        nama_ortu: "Johan",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1962,
        nama_ortu: "Jota",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1963,
        nama_ortu: "Jojo",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://media.creativemornings.com/uploads/user/avatar/49419/Bechtel_Profile_Square.jpg"
    },
    {
        id: 1964,
        nama_ortu: "Robert",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1965,
        nama_ortu: "Riski",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://media.creativemornings.com/uploads/user/avatar/49419/Bechtel_Profile_Square.jpg"
    },
    {
        id: 1966,
        nama_ortu: "Abi",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1967,
        nama_ortu: "Anda",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://media.creativemornings.com/uploads/user/avatar/49419/Bechtel_Profile_Square.jpg"
    },
    {
        id: 1968,
        nama_ortu: "Susi",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    },
    {
        id: 1969,
        nama_ortu: "Yanti",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "active",
        img: "https://media.creativemornings.com/uploads/user/avatar/49419/Bechtel_Profile_Square.jpg"
    },
    {
        id: 1970,
        nama_ortu: "Anton",
        alamat: "Raya Tenggilis 127 Apartment Metropolis B1210",
        bulan_masuk: "Lama",
        kota: "Surabaya",
        provinsi: "",
        email: "desipriyatiningsih@gmail.com",
        catatan: "Sudah mendapat pengajar tetapi lesnya selalu dibatalkan sepihak",
        regional: "Surabaya",
        status: "inactive",
        img: "https://www.stepstherapy.com.au/wp-content/uploads/2020/05/Natalie-square-profile-picture-1024x1024.jpg"
    }
]